### PR TITLE
Added search_documents API endpoint with documentation.

### PR DESCRIPTION
**Pull request by ShawnRye**
Also added tests to PR. Waiting on someone out of backend to check the merge before this goes into production.

### CODE REVIEW

**Comment by adams-k** [comment]
Please try to get the github actions to pass before merging.

**Comment by Jeremygoll** [comment]
Hey Shawn would you like some help getting this to pass the git hub actions?

**Comment by ShawnRye** [comment]
@adams-k Yup, Jeremy and I are aware of the issues in the PR. We are going to try to attempt to work on them before class.

**Comment by ShawnRye** [comment]
Closed because of merge issues with Jeremy's commit that couldn't easily be fixed; would be easier to make another PR.

**Pull request merged**
